# Generated by Django 4.2.4 on 2023-08-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.photo')),
            ],
        ),
    ]
